In [4]:
#Write a program to distinguish between Array Indexing and Fancy Indexing

import numpy as np
arr = np.array([10,20,30,40,50,60])
print("Array Indexing")
print( arr[4])
fancy = np.array([2,4,5])
print("Fancy Indexing")
print(arr[fancy])

Array Indexing
50
Fancy Indexing
[30 50 60]


In [11]:
#Execute the 2D array Slicing

import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("The Original Array: ")
print(arr)
print("2D array slicing array are: ")
print(arr[0:1, 3:4])
print(arr[::-2, ::-1])

The Original Array: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2D array slicing array are: 
[[4]]
[[10  9  8  7  6]]


In [12]:
#Create the 5-Dimensional arrays using ‘ndmin’

import numpy as np
arr = np.array([10,20,30,40,50], ndmin=5)
print(arr)

[[[[[10 20 30 40 50]]]]]


In [13]:
#Reshape the array from 1-D to 2-D array

import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90,100])
print(arr.reshape(2,5))

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [15]:
#Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack()

import numpy as np
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([60,70,80,90,100])

stack = np.stack((arr1, arr2))
print("The stack() array is: \n",stack)

hstack = np.hstack((arr1, arr2))
print("\nThe hstack() array is: \n",hstack)

vstack = np.vstack((arr1, arr2))
print("\nThe vstack() array is: \n",vstack)

dstack = np.dstack((arr1,arr2))
print("\nThe dstack array is: \n",dstack)


The stack() array is: 
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]

The hstack() array is: 
 [ 10  20  30  40  50  60  70  80  90 100]

The vstack() array is: 
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]

The dstack array is: 
 [[[ 10  60]
  [ 20  70]
  [ 30  80]
  [ 40  90]
  [ 50 100]]]


In [24]:
#Perform the searchsort method in Numpy array

import numpy as np
arr = np.array([10,20,50,40,30])
n = 10
search = np.searchsorted(arr, n)
print(search)

0


In [30]:
#Create Numpy Structured array using your domain features

import numpy as np

patient_dtype = np.dtype([
    ('patient_id', 'i4'),
    ('name', 'U30'),
    ('age', int),
    ('gender', 'U10'),
    ('admission_date', 'U20')
])

doctor_dtype = np.dtype([
    ('doctor_id', 'i4'),
    ('name', 'U30'),
    ('specialty', 'U30'),
    ('availability', 'bool')
])

patients = np.array([], dtype=patient_dtype)
doctors = np.array([], dtype=doctor_dtype)

patient_data = [
    (1, 'John Doe', 35, 'Male', '2023-09-16'),
    (2, 'Jane Smith', 45, 'Female', '2023-09-17'),
    (3, 'Smith', 25, 'male', '2023-09-20'),
    (4, 'Alex', 23, 'male', '2023-09-28'),
    (5, 'Henry', 24, 'male', '2023-09-28'),
]

doctor_data = [
    (101, 'Dr. Smith', 'Cardiology', True),
    (102, 'Dr. Johnson', 'Pediatrics', False),
    (103, 'Dr. James', 'Pediatrics', True),
    (104, 'Dr. Hardvard', 'Pediatrics', True),
    (105, 'Dr. Mary', 'Pediatrics', False),
]

patients = np.append(patients, np.array(patient_data, dtype=patient_dtype))
doctors = np.append(doctors, np.array(doctor_data, dtype=doctor_dtype))

print("Patients:")
print(patients)
print("\nDoctors:")
print(doctors)

Patients:
[(1, 'John Doe', 35, 'Male', '2023-09-16')
 (2, 'Jane Smith', 45, 'Female', '2023-09-17')
 (3, 'Smith', 25, 'male', '2023-09-20')
 (4, 'Alex', 23, 'male', '2023-09-28')
 (5, 'Henry', 24, 'male', '2023-09-28')]

Doctors:
[(101, 'Dr. Smith', 'Cardiology',  True)
 (102, 'Dr. Johnson', 'Pediatrics', False)
 (103, 'Dr. James', 'Pediatrics',  True)
 (104, 'Dr. Hardvard', 'Pediatrics',  True)
 (105, 'Dr. Mary', 'Pediatrics', False)]


In [34]:
#Create Data frame using List and Dictionary

import pandas as pd

dataframe = [
    {'Name': 'Alex', 'Age': 24, 'Gender': 'Male'},
     {'Name': 'Bob', 'Age': 22, 'Gender': 'Male'},
      {'Name': 'Henry', 'Age': 24, 'Gender': 'Male'},
       {'Name': 'Jane', 'Age': 27, 'Gender': 'Female'},
        {'Name': 'Mary', 'Age': 25, 'Gender': 'Female'}
]
df = pd.DataFrame(dataframe)
print("DataFrame are: ")
print(df)

DataFrame are: 
    Name  Age  Gender
0   Alex   24    Male
1    Bob   22    Male
2  Henry   24    Male
3   Jane   27  Female
4   Mary   25  Female


In [41]:
'''Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset'''

import pandas as pd
import numpy as np
dataframe = [
    {'Name': 'Alex', 'Age': np.nan, 'Gender': 'Male'},
     {'Name': 'Bob', 'Age': 22, 'Gender': np.nan},
      {'Name': 'Henry', 'Age': 24, 'Gender': np.nan},
       {'Name': 'Jane', 'Age': np.nan, 'Gender': 'Female'},
        {'Name': 'Mary', 'Age': 25, 'Gender': 'Female'}
]
df = pd.DataFrame(dataframe)
print("The dataframes are: ")
print(df)

print("\nBy using the isnull(): ")
print(df.isnull())

print("\By using the notnull(): ")
print(df.notnull())

df_dropp = df.dropna()
print("\nBy using dropna():")
print(df_dropp)

df_fille = df.fillna({'Age': df['Age'].mean()})
print("\nBy using fillna():")
print(df_fille)

df_replaced = df.replace({'Alex': 'Alexlader', 'Henry': 'Price'})
print("\nBy using replace():")
print(df_replaced)

df = df.infer_objects()
df_interpolated = df.interpolate()
print("\nBy using interpolate(): ")
print(df_interpolated)

The dataframes are: 
    Name   Age  Gender
0   Alex   NaN    Male
1    Bob  22.0     NaN
2  Henry  24.0     NaN
3   Jane   NaN  Female
4   Mary  25.0  Female

By using the isnull(): 
    Name    Age  Gender
0  False   True   False
1  False  False    True
2  False  False    True
3  False   True   False
4  False  False   False
\By using the notnull(): 
   Name    Age  Gender
0  True  False    True
1  True   True   False
2  True   True   False
3  True  False    True
4  True   True    True

By using dropna():
   Name   Age  Gender
4  Mary  25.0  Female

By using fillna():
    Name        Age  Gender
0   Alex  23.666667    Male
1    Bob  22.000000     NaN
2  Henry  24.000000     NaN
3   Jane  23.666667  Female
4   Mary  25.000000  Female

By using replace():
        Name   Age  Gender
0  Alexlader   NaN    Male
1        Bob  22.0     NaN
2      Price  24.0     NaN
3       Jane   NaN  Female
4       Mary  25.0  Female

By using interpolate(): 
    Name   Age  Gender
0   Alex   NaN    Male
1

In [45]:
#Perform the Hierarchical Indexing in the above created dataset

import pandas as pd
import numpy as np

dataframe = [
    {'Name': 'Alex', 'Age': np.nan, 'Gender': 'Male'},
     {'Name': 'Bob', 'Age': 22, 'Gender': np.nan},
      {'Name': 'Henry', 'Age': 24, 'Gender': np.nan},
       {'Name': 'Jane', 'Age': np.nan, 'Gender': 'Female'},
        {'Name': 'Mary', 'Age': 25, 'Gender': 'Female'}
]
df = pd.DataFrame(dataframe)
df['Hospital'] = ['Fortis', 'Aster', 'Jaydev', 'Ramaiah', 'Apollo']

df.set_index(['Hospital', 'Name'], inplace=True)

print("Dataframe after Hierarchical Indexing")
print(df)


Dataframe after Hierarchical Indexing
                 Age  Gender
Hospital Name               
Fortis   Alex    NaN    Male
Aster    Bob    22.0     NaN
Jaydev   Henry  24.0     NaN
Ramaiah  Jane    NaN  Female
Apollo   Mary   25.0  Female
